name: Sync DAGs to Composer

on:
  push:
    branches: [ main, feature/** ]
    paths:
      - 'dags/**'
      - '.github/workflows/sync-dags-to-composer.yml'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: winners-or-loosers
      BUCKET: gs://polygondata/dags

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Auth with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_CI_SA }}
          export_environment_variables: true

      - name: Sync DAGs
        run: |
          gsutil -m rsync -r dags $BUCKET


